Vagrant.configure(2) do |config|

  config.vm.define :dbsnp_host do |node|
    node.vm.box = "centos6"
    node.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.7_chef-provisionerless.box"

    node.vm.network :private_network, ip: "192.168.33.10"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook/site.yml"
      ansible.sudo = true
    end
  end

end
